Repository DD2480G19/teammates2, pull requests merged in 2023-03, with the labels that each got.

#46 feat: add test for unknown intent (#30)
  src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
Labels: New test

#50 resolves #49
  src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
Labels: New test

#47 resolves #22
  src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
  src/test/resources/data/typicalDataBundle.json
Labels: New test

#48 resolves #24
  src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
Labels: New test

#54 Fix: typicalDataBundle additions break tests (#51)
  src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
  src/test/resources/data/typicalDataBundle.json
Labels: bug

#52 Feat: Add test for valid student submission (#34)
  src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
Labels: bug, New test

#53 Doc: Add identified requirements to `README` (#12)
  README.md
Labels: documentation

#59 Feat: Add test for update response (ex08)
  src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
Labels: New test

#58 README: Fill in hours under "Effort spent"
  README.md
Labels: documentation

#73 Feat: Add test for ex10 (#45)
  src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
Labels: New test

#72 Feat: Add test for ex11 (#39)
  src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
  src/test/resources/data/typicalDataBundle.json
Labels: New test

#76 Refactor tests to mitigate code duplication (#60)
  src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
Labels: enhancement

#57 Feat: Add unit tests for ex03 and ex04 #36
  src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
  src/test/resources/data/typicalDataBundle.json
Labels: New test

#81 Refactor tests for ex03 and ex04 (#80)
  src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
Labels: enhancement

#78 Fix bug in ex08 test (#75)
  src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
Labels: bug

#79 Fix: Restore `typicalDataBundle.json` (#74)
  src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
  src/test/resources/data/typicalDataBundle.json
Labels: bug

#62 Doc: Add P+ criterion 6 part to README (#18)
  README.md
Labels: documentation

#82 Doc: Add to "Overall experience", the P parts might be done, but the …
  README.md
Labels: documentation

#83 doc: Added link to overview and purpose of system (#17)
  README.md
Labels: documentation

#85 Doc: Add test results to `README` (#14)
  README.md
Labels: documentation

#87 Doc: Add patch information to README (#84)
  README.md
Labels: documentation

#89 9 readme fill in hours under effort spent
  README.md
Labels: documentation
